### ISSUE TITLE
Function specifications and documentation: password decryption: Michelle

### ISSUE THREAD

**Issue by mishelly-h** [UBC-MDS/passwordler#10]

**Comment by mishelly-h** [comment]
I have a first draft of the docstrings for my function

**Comment by mishelly-h** [comment]
@zywkloo how are we going to encrypt / decrypt the passwords? Do you have a particular hash function / algorithm in mind?

**Comment by zywkloo** [comment]
https://github.com/UBC-MDS/passwordler/pull/12 The code is here. I have not installed the dependency and ran it locally, but basically, it's the idea.

**Comment by zywkloo** [comment]
A solution on Stackoverflow also covered decryption:
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import os
from Crypto.Cipher import AES  

BS = AES.block_size
pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS) 
unpad = lambda s: s[0:-ord(s[-1])]

def doEncrypt(phrase, key):
    c1 = AES.new(key, AES.MODE_ECB)  
    return c1.encrypt(pad(phrase))

def doDecrypt(phrase, key):
    c1 = AES.new(key, AES.MODE_ECB) 
    return unpad(c1.decrypt(phrase))

def testing123(phrase, key):
    encrypted = doEncrypt(phrase, key)
    decrypted = doDecrypt(encrypted, key)
    assert phrase == decrypted, "Encryption/Decryption verification failed"
    print ("Encryption/Decryption verified ok")
    print ('phrase/key(hex)/enc+dec: {}/{}/{}'.format(phrase, key.encode('hex'), decrypted))

if __name__== "__main__":
    phrase = 'Ala ma kota, a kot ma AIDS.'
    key = os.urandom(32)  # AES requires keys of length 16, 24, or 32 bytes
    testing123(phrase, key)
```

**Comment by zywkloo** [comment]
The AES algo implementation is dependent on the other library,  but that is pretty common. 
If you'd like to go with an independent implementation of encryption algo, you could try implementing encryption/decryption of Caesar Cipher (the idea is just to shift all 'a' to 'p', 'b' to 'q', 'c' to 'r', etc). However, it would be easy to crack, but might still be useful for educational purposes.
