### ISSUE TITLE
Team meeting Thursday 11th Jan

### ISSUE THREAD

**Issue by rorywhite200** [UBC-MDS/passwordler#15]
- @mishelly-h and @Kierst01 to update README to include contributing, license, installation etc
- @rorywhite200 can submit this week
- Add message to CONTRIBUTING, CONTRIBUTORS and CONDUCT to show that it was adapted from cookie cutter. Make small changes to reflect teamwork conduct.

**Comment by zywkloo** [comment]
Created the project Kanban, here is the url: https://github.com/orgs/UBC-MDS/projects/103
