### ISSUE TITLE
Interesting behaviour of test cases and merging

### ISSUE THREAD

**Issue by rorywhite200** [UBC-MDS/passwordler#46]
So Michelle's updates were still failing the test cases, even after Yiwei's changes were merged. As far as I understand, the reason for this is that the test cases check if commit itself passes the test cases, rather than examining whether the main repo would pass them if the commit was integrated.

Since Michelle's commit lacked some of the more recent files, like the ._internals file, it was failing the test cases. In this case, I decided to merge even though the test cases were failing. Lo and behold, the test cases passed after merging.

**Comment by zywkloo** [comment]
The ideal workflow is: 
 Always keep individual branches updated with `main`. Eg. after my branch merged to master, Michelle should merge the current `main` to her branch, resolve all the conflicts if any, and that makes sure the individual branch updated and all test cases and CI/CD checks pass.  Vice Versa.

**Comment by Kierst01** [comment]
I didn't know main could be merged into branches, thanks Yiwei. I'll make sure to do this as well going forward!

**Comment by zywkloo** [comment]
It was just a minor issue. Should have shared the knowledge during the meeting. No worry

> I didn't know main could be merged into branches, thanks Yiwei. I'll make sure to do this as well going forward!
