### ISSUE TITLE
Interesting bug related to random shuffling

### ISSUE THREAD

**Issue by rorywhite200** [UBC-MDS/passwordler#50]
I noticed that when you run 

```
cd tests
pytest test_internals.py::test_get_key_map_for_encryption
```

The test fails roughly 50% of the time due to the assert statement: assert all(key_map[orig] != orig for orig in original)

Exploring this further, I believe I have identified the cause. One of the failed mappings looked like this:

```
{'a': 'G', 'b': 'U', 'c': 'j', 'd': 'p', 'e': 'à', 'f': 'I', 'g': 'Z', 'h': 'c', 'i': '-', 'j': '.', 'k': '@', 'l': 'D', 'm': ',', 'n': 'f', 'o': '3', 'p': 'i', 'q': '%', 'r': 'K', 's': 'C', 't': 'é', 'u': 'y', 'v': '$', 'w': '8', 'x': 'E', 'y': 'ä', 'z': 'N', 'A': '?', 'B': '=', 'C': 'X', 'D': 'r', 'E': 'u', 'F': 'g', 'G': ':', 'H': '7', 'I': '6', 'J': 'S', 'K': '_', 'L': 'F', 'M': 'ü', 'N': 'B', 'O': 'Y', 'P': 'W', 'Q': 'a', 'R': 'O', 'S': '£', 'T': 'V', 'U': 'm', 'V': 'z', 'W': 'Q', 'X': '!', 'Y': 's', 'Z': 'A', 'é': '4', 'è': 'l', 'à': '1', 'ü': 'L', 'ö': 'o', 'ä': ' ', '0': 't', '1': 'x', '2': 'T', '3': 'P', '4': 'e', '5': '5', '6': 'b', '7': 'q', '8': 'k', '9': 'R', '.': 'è', ',': 'M', ';': '0', ':': 'H', '!': '2', '?': ';', '+': 'w', '@': 'J', '#': 'v', '%': '#', '&': 'ö', '$': 'd', '£': '9', '=': 'n', '-': '+', '_': 'h', ' ': '&'}
```

From this we see that 5 is mapped to 5, which causes the test to fail. This makes sense, as we have not implemented retrying to shuffle if characters are assigned to themselves. We should adapt our test cases or function to prepare for this eventuality.

**Comment by zywkloo** [comment]
Just changed the assert to `assert not all(key_map[orig] == orig for orig in original)`. This assertion fits better

**Comment by Kierst01** [comment]
This is very interesting, good catch! I think either changing the function or the test would work. I like Yiwei's assert statement :)
