### ISSUE TITLE
handy future feature for functions

### ISSUE THREAD

**Issue by rorywhite200** [UBC-MDS/passwordler#52]
I discovered the module string, which gives us access to a comprehensive list of characters of different types:

string.ascii_uppercase
string.digits
string.punctuation
string.ascii_letters
string.ascii_lowercase

I have integrated these into my password generation function as it is very convenient. We could consider using these in our shuffling / password strength too as they provide a more comprehensive set of characters. Currently, many of these will not be shuffled during encryption.

**Comment by rorywhite200** [comment]
its a built in python module too

**Comment by zywkloo** [comment]
It's a good point to enhance the hard-coded `original` dictionary. We could leave this issue open until milestone 4 or a better solution is implemented.
Thanks.

**Comment by Kierst01** [comment]
Thanks Rory, I used Regex in my password_strength function, but this would work too. I can look into using these instead going forward, if they are more comprehensive it might be better

**Comment by zywkloo** [comment]
Just updated our encryption/decryption vocabulary with `string` library built-in constants, pretty handy.
