### ISSUE TITLE
Share knowledge about how to link an issue to a branch

### ISSUE THREAD

**Issue by zywkloo** [UBC-MDS/passwordler#55]
1. Assign the issue to yourself
<img width="379" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/9aea588a-1abe-4090-9342-38f3926e8a0f">
<img width="331" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/57386697-99cf-4b0f-9939-97ec86da7cd6">

2. Assign the issue to the project(board):
<img width="400" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/8923e1bc-828a-40f1-b8eb-4a1a2e6e9a1f">
<img width="391" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/8f7b6386-efd4-47ad-b927-241f2e246227">

3. Assign it to a proper milestone.
<img width="359" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/2b658b99-b60a-447c-ad1a-3cb4376029bd">

**Comment by zywkloo** [comment]
4. Once created, assign a status (ready, in progress or anything you need)
<img width="388" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/450e1998-3da0-476b-9805-5e77b9dfeee0">

**Comment by zywkloo** [comment]
5. Create a new branch(will be automatically linked to the issue), 
<img width="358" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/ab0bd48d-e1ac-4795-8306-a0dbf0f90da7">
 
Or link an existing branch to it:

<img width="412" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/728fc547-ab56-4ffb-b3c8-55181b419f44">

<img width="361" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/e4b5f4ba-7a64-4b84-a579-910bfb2a4faa">

**Comment by zywkloo** [comment]
Done!
Congrats, now the issue and PR are linked!
<img width="357" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/df556b85-ef09-4ecf-a4a1-53b724dfa016">


Drag the issue on the project board will change the issue status automatically, and merging the PR successfully will close the issue.
<img width="904" alt="image" src="https://github.com/UBC-MDS/passwordler/assets/18610590/e83d92cd-22f8-4e52-9623-bc73d4a166f9">

**Comment by Kierst01** [comment]
Thanks Yiwei! This is super helpful :)
