### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by Kierst01** [UBC-MDS/passwordler#76]
- [x] Expand comparison between our package and existing packages
- [x] Add more badges for continuous integration, Python version compatibility, and the current package version
- [x] Add backticks to function names
- [x] Change installation instructions into smaller more explicit steps
- [x] Include link to ReadTheDocs (other than the badge link)

Additional if desired: Add a logo

**Comment by rorywhite200** [comment]
Read me file says to use release 2.0, we need to change this

**Comment by Kierst01** [comment]
> Read me file says to use release 2.0, we need to change this

When I updated the installation instructions it removed this comment! So should be good now

**Comment by zywkloo** [comment]
https://github.com/orgs/UBC-MDS/projects/103/views/1?pane=issue&itemId=51760310
This issue is also related to updating the Readme. It's in Reveiw now.


Done.
