### ISSUE TITLE
Function Improvements

### ISSUE THREAD

**Issue by Kierst01** [UBC-MDS/passwordler#78]
- [x] 1. Add examples to our function docstrings
- [x] 2. Update functions to use string.ascii. Fix in 0657c89e8adb0ad90b7046e30e3a6de9894f7fd0, 82df255ecf41eb07f42891a713b94f3f5f7adce9, 39a25c5506569f892d78a18f742ab00808cd1575

  - [ ] 3. Separate cypher shuffling for encryption and decryption so they do not become uncoupled with future updates
 Decided to not update: As the original way decouple the functions better.

  - [ ] 4. Update password generator to include an argument for lower/uppercase characters
 Decided to not update: That may require restructuring the whole function.

**Comment by mishelly-h** [comment]
I am adding the function examples now

**Comment by zywkloo** [comment]
2. Update functions to use string.ascii 。 
3. Separate cypher shuffling for encryption and decryption so they do not become uncoupled with future updates
4. Update password generator to include an argument for lower/uppercase characters

**Comment by zywkloo** [comment]
Re-evaluate the requirements. And close the issues.
